language: java
sudo: true
services:
  - docker
jdk:
  - openjdk11

install: skip #skip install impliclty done on each stage by travis

#  - docker build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
#  - docker run -d -p 127.0.0.1:8080:8080 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}

#script:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}

jobs:
  include:
    - stage: test
      script:
        - echo "test the application"
        - mvn clean install
      before_install:
        - chmod +x mvnw
    - stage: docker_build_push
      script: ./docker-build.sh
      before_install:
        - chmod +x docker-build.sh

#
#after_success:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "stable"; else echo $TRAVIS_BRANCH; fi`
#  - export DOCKER_IMAGE_NAME=surazneg/data-generator
#  - docker build -t $DOCKER_IMAGE_NAME:$TRAVIS_COMMIT .
#  - docker tag $DOCKER_IMAGE_NAME:$TRAVIS_COMMIT $DOCKER_IMAGE_NAME:$TAG
#  - docker push $DOCKER_IMAGE_NAME:$TAG

