language: java
sudo: true
services:
  - docker
jdk:
  - openjdk11

install: skip #skip install impliclty done on each stage by travis

jobs:
  include:
    - stage: test
      script:
        - echo "test the application"
        - mvn clean install
      before_install:
        - chmod +x mvnw
    - stage: docker_build_push
      script: ./docker-build.sh
      before_install:
        - chmod +x docker-build.sh
