language: java
sudo: true
services:
  - docker
jdk:
  - openjdk11

before_install:
  - chmod +x mvnw
  - chmod +x docker-build.sh

install: true #skip install implicitly done on each stage by travis


script:
  - ./mvnw clean install
  - ./docker-build.sh

#jobs:
#  include:
#    - stage: test
#      script:
#        - echo "test the application"
#        - mvn clean install
#      before_install:
#        - chmod +x mvnw
#    - stage: docker_build_push
#      script: ./docker-build.sh
#      before_install:
#        - chmod +x docker-build.sh
