
data:
  keys:
    objToObjCheck:
      type: object
      data:
        checkpoint: objToObjCheck
        keys:
          name:
            type: constant
            generator: mock
            data_type: string
            value: name.firstName
          id:
            type: constant
            generator: regex
            value: "[0-9](3)[1-9](1)"
            data_type: string
            checkpoint: id
    objToObjCheck2:
      type: object
      data:
        use: objToObjCheck

    listToList:
      type: list
      max_len: 5
      min_len: 2
      checkpoint: listToList1
      index:
        type: constant
        data_type: int
        generator: mock
        value: name.firstName
    listToList2:
      type: list
      index:
        type: list
        use:  listToList1


#
#    batters:
#      type: object
#      data:
#        keys:
#          batter:
#            type: list
#            min_len: 3
#            max_len: 8
#            index:
#              type: object
#              data:
#                keys:
#                  id:
#                    type: constant
#                    data_type: string
#                    generator: regex
#                    value: "[1-9](1)[0-9](3)"
#                  type:
#                    type: constant
#                    value_in: ["chocolate","vanilla","blueberry","strawberry"]
#                    data_type: string
#    topping:
#      type: list
#      min_len: 4
#      max_len: 4
#      index:
#        type: object
#        data:
#          keys:
#            id:
#              type: constant
#              data_type: string
#              generator: regex
#              value: "[5](1)[0-9](3)"
#            type:
#              type: constant
#              value_in: ["none","glazed","sugar","maple","powdered","chocolate"]
#              data_type: string
