
count: 4

variables:
  id: idNumber.ssnValid
  first_name: name.firstName
  last_name: name.lastName
  zipcode: address.zipCode
  state: address.state
  city: address.city
  sample: address.city






schema:
  type: objectData
  keys:
    - key: id
      type: fieldData
      value: id
    - key: first_name
      type: fieldData
      value: first_name
    - key: last_name
      type: fieldData
      value: last_name
    - key: interests
      type: listData
      min_len: 3
      max_len: 5
      index:
        type: listData
        min_len: 3
        max_len: 4
        index:
          type: objectData
          keys:
            - key: type
              type: fieldData
              value: sample
            - key: type
              type: fieldData
              value: sample